Return false if instanceuser is None
fixes

"""
ERROR: test_plot_detail (treemap.tests.urls.TreemapUrlTests)

[localhost] out:   File "/usr/local/otm/app/opentreemap/treemap/templatetags/instance_config.py", line 50, in is_deletable
[localhost] out:     return obj.user_can_delete(instanceuser.user)
[localhost] out: AttributeError: 'NoneType' object has no attribute 'user'
"""