Fixes a bug with a unit test failing at certain times of day.
https://travis-ci.org/OpenTreeMap/OTM2/builds/43048572 failed with the
following output:
 File "/home/travis/build/OpenTreeMap/OTM2/opentreemap/treemap/tests/dates.py",
 line 44, in test_mixed_tz_awareness_neq

 d2 = datetime(d1.year, d1.month, d1.day, d1.hour - 1)

 ValueError: hour must be in 0..23

The test took place at around 7:30PM ET, which would put it at 12:30PM UTC.
This caused d1.hour to be 0, which meant d1.hour - 1 was -1, and invalid value.